---
application-id: kq9Dra2hwGN
server-url: "http://localhost:8080"
application-info:
  home-page: "https://github.com/bitshifted/ignite-maven-plugin"
  authors:
    - name: John Doe
      email: john@doe.com
      website: "https://www.johndoe.com"
  license:
    source: "GPLv2"
    target: LICENSE
  exe-name: "simplejavafx"
  splash-screen:
    source: "splash.png"
  windows:
    icons:
      - source: "icon_win.ico"
  linux:
    categories:
      - "Development"
      - "Building"
    icons:
      - source: "icon_x48.png"
      - source: "icon_x64.png"
    supported-cpu-arch:
      - "X64"
      - "AARCH64"
    packageTypes:
      - "TAR_GZ"
      - "RPM"
      - "DEB"
  mac:
    icons:
      - source: "icon_osx.icns"
jvm:
  vendor: ADOPTIUM
  major-version: "17"
  release: "latest"
  jvm-options: "-Xms10m -Xmx120m"
  system-properties: "-Dprop1=value1 -Dprop2=value2"
  main-class: com.test.TestFX.TestFX
  #jar: my-artifact.jar # either jar or main-class should be specified
  module-name: com.test.testfx # module name in case app is modular
  arguments: "arg1 arg2"
resources:
  - source: files
  - source: GPLv2
    target: LICENSE
