---
id: 1234adf
server-url: "http://localhost:8080"
application-info:
  splash-screen:
    source: "splash.png"
  windows:
    icons:
      - source: "icon_win.ico"
  linux:
    icons:
      - source: "icon_x48.png"
      - source: "icon_x64.png"
  mac:
    icons:
      - source: "icon_osx.icns"
jvm:
  vendor: ADOPTIUM
  major-version: "17"
  jvm-options: "-Xms10m -Xmx120m"
  system-properties: "-Dprop1=value1 -Dprop2=value2"
  main-class: com.myapp.MainClass
  jar: my-artifact.jar # either jar or main-class should be specified
  module-name: mymodule # module name in case app is modular
  arguments: "arg1 arg2"
resources:
  - source: files
  - source: GPLv2
    target: LICENSE
