---
application-id: qpBdwMxiG1m
server-url: "http://localhost:8080"
application-info:
  license:
    source: "GPLv3"
    target: LICENSE
  exe-name: simpleswing
  splash-screen:
    source: "splash.png"
  windows:
    icons:
      - source: "icon_win.ico"
  linux:
    icons:
      - source: "icon_x48.png"
      - source: "icon_x64.png"
  mac:
    icons:
      - source: "icon_osx.icns"
jvm:
  vendor: ADOPTIUM
  major-version: "8"
  jvm-options: "-Xms10m -Xmx120m"
  system-properties: "-Dprop1=value1 -Dprop2=value2"
  main-class: org.example.SwingTest
  arguments: "arg1 arg2"
resources:
  - source: GPLv3
    target: LICENSE

