name: Perform code verification
on:
  - pull_request:
  - push:
      branches: [ main ]
      paths-ignore:
        - 'version'
jobs:
  install-java:
    runs-on: ubuntu-latest
    steps:
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and run tests
        run: |
          mvn install
